local DHUD = DHUD

DHUD.Language = DHUD.Language or {}

DHUD.Language.Available = {
    {Code = "en", Name = "English"},
    {Code = "es", Name = "Spanish"},
    {Code = "fr", Name = "French"},
    {Code = "de", Name = "German"},
    {Code = "pt_br", Name = "Portuguese (Brazil)"}
}

local function Merge(dst, src)
    dst = dst or {}
    for key, value in next, (src or {}) do
        dst[key] = value
    end
    return dst
end

local en = {
    ["vehicle.health"] = "Health",
    ["vehicle.fuel"] = "Fuel",
    ["config.language"] = "Language",
    ["config.language_hint"] = "Client-facing HUD labels that have language entries.",

    ["Overview"] = "Overview",
    ["Theme"] = "Theme",
    ["HUD"] = "HUD",
    ["Weapon Selector"] = "Weapon Selector",
    ["Death Screen"] = "Death Screen",
    ["Scoreboard"] = "Scoreboard",
    ["Leaderboards"] = "Leaderboards",
    ["MOTD"] = "MOTD",
    ["Feeds"] = "Feeds",
    ["Supported Scripts"] = "Supported Scripts",
    ["Credit System"] = "Credit System",
    ["System Overview"] = "System Overview",
    ["Core HUD behavior and quick workspace actions."] = "Core HUD behavior and quick workspace actions.",
    ["Language & Localization"] = "Language & Localization",
    ["Choose the language used by built-in HUD and menu labels."] = "Choose the language used by built-in HUD and menu labels.",
    ["Active HUD layout"] = "Active HUD layout",
    ["Bar HUD"] = "Bar HUD",
    ["Card HUD"] = "Card HUD",
    ["Clock source"] = "Clock source",
    ["Real world time"] = "Real world time",
    ["Atmos / in-game time"] = "Atmos / in-game time",
    ["Admin command system"] = "Admin command system",
    ["Auto detect"] = "Auto detect",
    ["ServerGuard / Custom"] = "ServerGuard / Custom",
    ["Interface Sounds"] = "Interface Sounds",
    ["Hover sound behavior for interactive HUD controls."] = "Hover sound behavior for interactive HUD controls.",
    ["Enable hover sounds"] = "Enable hover sounds",
    ["Hover sound preset"] = "Hover sound preset",
    ["Rollover"] = "Rollover",
    ["Soft click"] = "Soft click",
    ["Blip"] = "Blip",
    ["Tick"] = "Tick",
    ["Animation Menu"] = "Animation Menu",
    ["DarkRP gesture/action menu override."] = "DarkRP gesture/action menu override.",
    ["Enable animation menu override"] = "Enable animation menu override",
    ["Animation menu title"] = "Animation menu title",
    ["Animation menu subtitle"] = "Animation menu subtitle",
    ["Animation menu width"] = "Animation menu width",
    ["Animation row height"] = "Animation row height",
    ["Animation menu horizontal position"] = "Animation menu horizontal position",
    ["Connection Overlay"] = "Connection Overlay",
    ["Fullscreen crash / reconnect panel behavior."] = "Fullscreen crash / reconnect panel behavior.",
    ["Enable lost connection overlay"] = "Enable lost connection overlay",
    ["Lost connection timeout"] = "Lost connection timeout",
    ["Auto retry connection"] = "Auto retry connection",
    ["Auto retry delay"] = "Auto retry delay",
    ["Use background blur"] = "Use background blur",
    ["Show disconnect button"] = "Show disconnect button",
    ["Apply"] = "Apply",
    ["Placement"] = "Placement",
    ["Placement Mode"] = "Placement Mode",
    ["Drag a stack to move it. Drop it on Trash to hide it, or restore it from the element list."] = "Drag a stack to move it. Drop it on Trash to hide it, or restore it from the element list.",

    ["Theme Presets"] = "Theme Presets",
    ["Fast starting points. Save after applying if you want to keep one."] = "Fast starting points. Save after applying if you want to keep one.",
    ["Background"] = "Background",
    ["Panel"] = "Panel",
    ["Field"] = "Field",
    ["Accent"] = "Accent",
    ["Save"] = "Save",
    ["Reset"] = "Reset",
    ["Confirm"] = "Confirm",
    ["Cancel"] = "Cancel",
    ["Close"] = "Close",
    ["Enabled"] = "Enabled",
    ["Disabled"] = "Disabled",
    ["Title"] = "Title",
    ["Subtitle"] = "Subtitle",
    ["Width"] = "Width",
    ["Height"] = "Height",
    ["X position"] = "X position",
    ["Y position"] = "Y position",
    ["Icon"] = "Icon",
    ["Label"] = "Label",
    ["URL"] = "URL",
    ["Action"] = "Action",
    ["Name"] = "Name",
    ["Color"] = "Color",
    ["Order"] = "Order",
    ["Preview"] = "Preview",

    ["Welcome"] = "Welcome",
    ["Welcome to the Server"] = "Welcome to the Server",
    ["Read the rules, respect the RP, and have a good time."] = "Read the rules, respect the RP, and have a good time.",
    ["Server Updates"] = "Server Updates",
    ["Rules"] = "Rules",
    ["Link"] = "Link",
    ["Discord"] = "Discord",
    ["Website"] = "Website",
    ["Shop"] = "Shop",
    ["Respect staff and other players."] = "Respect staff and other players.",
    ["Stay in character during RP situations."] = "Stay in character during RP situations.",
    ["Do not RDM, prop abuse, or exploit."] = "Do not RDM, prop abuse, or exploit.",
    ["Use the scoreboard for quick player actions and server info."] = "Use the scoreboard for quick player actions and server info.",
    ["New HUD systems are being tested."] = "New HUD systems are being tested.",
    ["Use F1 for laws and TAB for the scoreboard."] = "Use F1 for laws and TAB for the scoreboard.",

    ["Wallet"] = "Wallet",
    ["Health"] = "Health",
    ["Armor"] = "Armor",
    ["Hunger"] = "Hunger",
    ["Oxygen"] = "Oxygen",
    ["Props"] = "Props",
    ["Ammo"] = "Ammo",
    ["Agenda"] = "Agenda",
    ["Laws"] = "Laws",
    ["Laws - F1"] = "Laws - F1",
    ["Laws of the Land"] = "Laws of the Land",
    ["No laws are posted."] = "No laws are posted.",
    ["Unknown"] = "Unknown",
    ["Weapon"] = "Weapon",
    ["Vehicle HUD"] = "Vehicle HUD",
    ["Fuel"] = "Fuel",

    ["You Died"] = "You Died",
    ["Down but not out"] = "Down but not out",
    ["Respawn when ready"] = "Respawn when ready",
    ["Take a breath. You can respawn when the server allows it."] = "Take a breath. You can respawn when the server allows it.",
    ["Press {key} to respawn"] = "Press {key} to respawn",
    ["Any Key"] = "Any Key",
    ["Mouse 1"] = "Mouse 1",
    ["Space"] = "Space",
    ["Enter"] = "Enter",

    ["Connection Interrupted"] = "Connection Interrupted",
    ["Trying to reconnect to the server..."] = "Trying to reconnect to the server...",
    ["Disconnect"] = "Disconnect",
    ["Retry"] = "Retry",
    ["Retry Now"] = "Retry Now",
    ["Waiting for server response"] = "Waiting for server response",
    ["Auto reconnect in {seconds}s"] = "Auto reconnect in {seconds}s",

    ["Notifications"] = "Notifications",
    ["Death Feed"] = "Death Feed",
    ["Voice HUD"] = "Voice HUD",
    ["Vote UI"] = "Vote UI",
    ["Wanted / Lockdown"] = "Wanted / Lockdown",
    ["Lost Connection"] = "Lost Connection",
    ["Ammo HUD"] = "Ammo HUD",
    ["Notification"] = "Notification",
    ["Example server popup"] = "Example server popup",
    ["Queued notification"] = "Queued notification",
    ["Death feed queue item"] = "Death feed queue item",
    ["Trash"] = "Trash",
    ["Restore"] = "Restore",

    ["Actions Menu"] = "Actions Menu",
    ["Choose a gesture"] = "Choose a gesture",
    ["Bow"] = "Bow",
    ["Sexy Dance"] = "Sexy Dance",
    ["Follow Me"] = "Follow Me",
    ["Laugh"] = "Laugh",
    ["Lion Pose"] = "Lion Pose",
    ["No"] = "No",
    ["Thumbs Up"] = "Thumbs Up",
    ["Wave"] = "Wave",
    ["Dance"] = "Dance",

    ["Enter"] = "Enter",
    ["Approve"] = "Approve",
    ["Yes"] = "Yes",
    ["Skip"] = "Skip",
    ["Deny"] = "Deny",
    ["No"] = "No",

    ["Door"] = "Door",
    ["Door Options"] = "Door Options",
    ["Buy Door"] = "Buy Door",
    ["Sell Door"] = "Sell Door",
    ["Lock"] = "Lock",
    ["Unlock"] = "Unlock",
    ["Ownable"] = "Ownable",
    ["Owned"] = "Owned",
    ["Unowned"] = "Unowned"
}

local es = {
    ["vehicle.health"] = "Salud",
    ["vehicle.fuel"] = "Combustible",
    ["config.language"] = "Idioma",
    ["config.language_hint"] = "Etiquetas del HUD con traducciones disponibles.",
    ["Overview"] = "Resumen",
    ["Theme"] = "Tema",
    ["HUD"] = "HUD",
    ["Weapon Selector"] = "Selector de armas",
    ["Death Screen"] = "Pantalla de muerte",
    ["Scoreboard"] = "Marcador",
    ["Leaderboards"] = "Clasificaciones",
    ["Feeds"] = "Avisos",
    ["Supported Scripts"] = "Scripts compatibles",
    ["Credit System"] = "Sistema de creditos",
    ["System Overview"] = "Resumen del sistema",
    ["Core HUD behavior and quick workspace actions."] = "Comportamiento principal del HUD y acciones rapidas.",
    ["Language & Localization"] = "Idioma y localizacion",
    ["Choose the language used by built-in HUD and menu labels."] = "Elige el idioma usado por las etiquetas integradas del HUD y los menus.",
    ["Language"] = "Idioma",
    ["Active HUD layout"] = "Diseno activo del HUD",
    ["Bar HUD"] = "HUD de barra",
    ["Card HUD"] = "HUD de tarjeta",
    ["Clock source"] = "Fuente del reloj",
    ["Real world time"] = "Hora real",
    ["Atmos / in-game time"] = "Atmos / hora del juego",
    ["Admin command system"] = "Sistema de comandos admin",
    ["Auto detect"] = "Detectar automaticamente",
    ["ServerGuard / Custom"] = "ServerGuard / personalizado",
    ["Interface Sounds"] = "Sonidos de interfaz",
    ["Hover sound behavior for interactive HUD controls."] = "Sonido al pasar el cursor sobre controles del HUD.",
    ["Enable hover sounds"] = "Activar sonidos al pasar el cursor",
    ["Hover sound preset"] = "Sonido al pasar el cursor",
    ["Rollover"] = "Rollover",
    ["Soft click"] = "Clic suave",
    ["Blip"] = "Blip",
    ["Tick"] = "Tick",
    ["Animation Menu"] = "Menu de animaciones",
    ["DarkRP gesture/action menu override."] = "Reemplazo del menu de gestos/acciones de DarkRP.",
    ["Enable animation menu override"] = "Activar reemplazo del menu de animaciones",
    ["Animation menu title"] = "Titulo del menu de animaciones",
    ["Animation menu subtitle"] = "Subtitulo del menu de animaciones",
    ["Animation menu width"] = "Ancho del menu de animaciones",
    ["Animation row height"] = "Alto de fila de animacion",
    ["Animation menu horizontal position"] = "Posicion horizontal del menu de animaciones",
    ["Connection Overlay"] = "Panel de conexion",
    ["Fullscreen crash / reconnect panel behavior."] = "Comportamiento del panel de caida / reconexion.",
    ["Enable lost connection overlay"] = "Activar panel de conexion perdida",
    ["Lost connection timeout"] = "Tiempo para conexion perdida",
    ["Auto retry connection"] = "Reintentar conexion automaticamente",
    ["Auto retry delay"] = "Retraso de reintento",
    ["Use background blur"] = "Usar desenfoque de fondo",
    ["Show disconnect button"] = "Mostrar boton de desconexion",
    ["Apply"] = "Aplicar",
    ["Placement"] = "Colocacion",
    ["Placement Mode"] = "Modo de colocacion",
    ["Drag a stack to move it. Drop it on Trash to hide it, or restore it from the element list."] = "Arrastra un grupo para moverlo. Sueltalo en Papelera para ocultarlo o restauralo desde la lista.",
    ["Theme Presets"] = "Presets de tema",
    ["Fast starting points. Save after applying if you want to keep one."] = "Puntos de inicio rapidos. Guarda despues de aplicar para conservar uno.",
    ["Background"] = "Fondo",
    ["Panel"] = "Panel",
    ["Field"] = "Campo",
    ["Accent"] = "Acento",
    ["Save"] = "Guardar",
    ["Reset"] = "Restablecer",
    ["Confirm"] = "Confirmar",
    ["Cancel"] = "Cancelar",
    ["Close"] = "Cerrar",
    ["Enabled"] = "Activado",
    ["Disabled"] = "Desactivado",
    ["Title"] = "Titulo",
    ["Subtitle"] = "Subtitulo",
    ["Width"] = "Ancho",
    ["Height"] = "Alto",
    ["X position"] = "Posicion X",
    ["Y position"] = "Posicion Y",
    ["Icon"] = "Icono",
    ["Label"] = "Etiqueta",
    ["URL"] = "URL",
    ["Action"] = "Accion",
    ["Name"] = "Nombre",
    ["Color"] = "Color",
    ["Order"] = "Orden",
    ["Preview"] = "Vista previa",
    ["Welcome"] = "Bienvenido",
    ["Welcome to the Server"] = "Bienvenido al servidor",
    ["Read the rules, respect the RP, and have a good time."] = "Lee las reglas, respeta el RP y pasalo bien.",
    ["Server Updates"] = "Novedades del servidor",
    ["Rules"] = "Reglas",
    ["Link"] = "Enlace",
    ["Discord"] = "Discord",
    ["Website"] = "Sitio web",
    ["Shop"] = "Tienda",
    ["Respect staff and other players."] = "Respeta al staff y a otros jugadores.",
    ["Stay in character during RP situations."] = "Mantente en personaje durante situaciones RP.",
    ["Do not RDM, prop abuse, or exploit."] = "No hagas RDM, abuso de props ni exploits.",
    ["Use the scoreboard for quick player actions and server info."] = "Usa el marcador para acciones rapidas e info del servidor.",
    ["New HUD systems are being tested."] = "Se estan probando nuevos sistemas del HUD.",
    ["Use F1 for laws and TAB for the scoreboard."] = "Usa F1 para leyes y TAB para el marcador.",
    ["Wallet"] = "Cartera",
    ["Health"] = "Salud",
    ["Armor"] = "Armadura",
    ["Hunger"] = "Hambre",
    ["Oxygen"] = "Oxigeno",
    ["Props"] = "Props",
    ["Ammo"] = "Municion",
    ["Agenda"] = "Agenda",
    ["Laws"] = "Leyes",
    ["Laws - F1"] = "Leyes - F1",
    ["Laws of the Land"] = "Leyes del servidor",
    ["No laws are posted."] = "No hay leyes publicadas.",
    ["Unknown"] = "Desconocido",
    ["Weapon"] = "Arma",
    ["Vehicle HUD"] = "HUD de vehiculo",
    ["Fuel"] = "Combustible",
    ["You Died"] = "Has muerto",
    ["Down but not out"] = "Caido, pero no fuera",
    ["Respawn when ready"] = "Reaparece cuando estes listo",
    ["Take a breath. You can respawn when the server allows it."] = "Respira. Podras reaparecer cuando el servidor lo permita.",
    ["Press {key} to respawn"] = "Pulsa {key} para reaparecer",
    ["Any Key"] = "Cualquier tecla",
    ["Mouse 1"] = "Raton 1",
    ["Space"] = "Espacio",
    ["Enter"] = "Entrar",
    ["Connection Interrupted"] = "Conexion interrumpida",
    ["Trying to reconnect to the server..."] = "Intentando reconectar al servidor...",
    ["Disconnect"] = "Desconectar",
    ["Retry"] = "Reintentar",
    ["Retry Now"] = "Reintentar ahora",
    ["Waiting for server response"] = "Esperando respuesta del servidor",
    ["Auto reconnect in {seconds}s"] = "Reconectar automaticamente en {seconds}s",
    ["Notifications"] = "Notificaciones",
    ["Death Feed"] = "Feed de muertes",
    ["Voice HUD"] = "HUD de voz",
    ["Vote UI"] = "Interfaz de voto",
    ["Wanted / Lockdown"] = "Buscado / toque de queda",
    ["Lost Connection"] = "Conexion perdida",
    ["Ammo HUD"] = "HUD de municion",
    ["Example server popup"] = "Aviso de ejemplo",
    ["Queued notification"] = "Notificacion en cola",
    ["Death feed queue item"] = "Elemento del feed de muertes",
    ["Trash"] = "Papelera",
    ["Restore"] = "Restaurar",
    ["Actions Menu"] = "Menu de acciones",
    ["Choose a gesture"] = "Elige un gesto",
    ["Bow"] = "Reverencia",
    ["Sexy Dance"] = "Baile",
    ["Follow Me"] = "Sigueme",
    ["Laugh"] = "Reir",
    ["Lion Pose"] = "Pose",
    ["No"] = "No",
    ["Thumbs Up"] = "Pulgar arriba",
    ["Wave"] = "Saludar",
    ["Dance"] = "Bailar",
    ["Approve"] = "Aprobar",
    ["Yes"] = "Si",
    ["Skip"] = "Saltar",
    ["Deny"] = "Denegar",
    ["Door"] = "Puerta",
    ["Door Options"] = "Opciones de puerta",
    ["Buy Door"] = "Comprar puerta",
    ["Sell Door"] = "Vender puerta",
    ["Lock"] = "Cerrar",
    ["Unlock"] = "Abrir",
    ["Ownable"] = "Comprable",
    ["Owned"] = "Comprada",
    ["Unowned"] = "Sin dueno"
}

local fr = {
    ["vehicle.health"] = "Sante",
    ["vehicle.fuel"] = "Carburant",
    ["config.language"] = "Langue",
    ["config.language_hint"] = "Libelles du HUD avec traductions disponibles.",
    ["Overview"] = "Apercu",
    ["Theme"] = "Theme",
    ["Weapon Selector"] = "Selecteur d'armes",
    ["Death Screen"] = "Ecran de mort",
    ["Scoreboard"] = "Tableau des scores",
    ["Leaderboards"] = "Classements",
    ["Feeds"] = "Flux",
    ["Supported Scripts"] = "Scripts pris en charge",
    ["Credit System"] = "Systeme de credits",
    ["System Overview"] = "Apercu du systeme",
    ["Core HUD behavior and quick workspace actions."] = "Comportement principal du HUD et actions rapides.",
    ["Language & Localization"] = "Langue et localisation",
    ["Choose the language used by built-in HUD and menu labels."] = "Choisis la langue des libelles integres du HUD et des menus.",
    ["Language"] = "Langue",
    ["Active HUD layout"] = "Disposition active du HUD",
    ["Bar HUD"] = "HUD en barre",
    ["Card HUD"] = "HUD en carte",
    ["Clock source"] = "Source de l'horloge",
    ["Real world time"] = "Heure reelle",
    ["Atmos / in-game time"] = "Atmos / heure en jeu",
    ["Admin command system"] = "Systeme de commandes admin",
    ["Auto detect"] = "Detection auto",
    ["ServerGuard / Custom"] = "ServerGuard / personnalise",
    ["Interface Sounds"] = "Sons d'interface",
    ["Hover sound behavior for interactive HUD controls."] = "Son au survol des controles interactifs du HUD.",
    ["Enable hover sounds"] = "Activer les sons de survol",
    ["Hover sound preset"] = "Son de survol",
    ["Soft click"] = "Clic doux",
    ["Animation Menu"] = "Menu d'animations",
    ["DarkRP gesture/action menu override."] = "Remplacement du menu gestes/actions DarkRP.",
    ["Enable animation menu override"] = "Activer le remplacement du menu d'animations",
    ["Connection Overlay"] = "Panneau de connexion",
    ["Enable lost connection overlay"] = "Activer le panneau de connexion perdue",
    ["Lost connection timeout"] = "Delai de connexion perdue",
    ["Auto retry connection"] = "Reessayer automatiquement",
    ["Auto retry delay"] = "Delai de reessai",
    ["Use background blur"] = "Utiliser le flou d'arriere-plan",
    ["Show disconnect button"] = "Afficher le bouton de deconnexion",
    ["Apply"] = "Appliquer",
    ["Placement"] = "Placement",
    ["Placement Mode"] = "Mode placement",
    ["Save"] = "Sauvegarder",
    ["Reset"] = "Reinitialiser",
    ["Confirm"] = "Confirmer",
    ["Cancel"] = "Annuler",
    ["Close"] = "Fermer",
    ["Enabled"] = "Active",
    ["Disabled"] = "Desactive",
    ["Title"] = "Titre",
    ["Subtitle"] = "Sous-titre",
    ["Width"] = "Largeur",
    ["Height"] = "Hauteur",
    ["Preview"] = "Apercu",
    ["Welcome"] = "Bienvenue",
    ["Welcome to the Server"] = "Bienvenue sur le serveur",
    ["Read the rules, respect the RP, and have a good time."] = "Lis les regles, respecte le RP et amuse-toi.",
    ["Server Updates"] = "Nouveautes du serveur",
    ["Rules"] = "Regles",
    ["Website"] = "Site web",
    ["Shop"] = "Boutique",
    ["Respect staff and other players."] = "Respecte le staff et les autres joueurs.",
    ["Stay in character during RP situations."] = "Reste dans ton role pendant les situations RP.",
    ["Do not RDM, prop abuse, or exploit."] = "Pas de RDM, d'abus de props ou d'exploit.",
    ["Use the scoreboard for quick player actions and server info."] = "Utilise le tableau des scores pour les actions rapides et infos serveur.",
    ["New HUD systems are being tested."] = "De nouveaux systemes HUD sont testes.",
    ["Use F1 for laws and TAB for the scoreboard."] = "Utilise F1 pour les lois et TAB pour le tableau.",
    ["Wallet"] = "Portefeuille",
    ["Health"] = "Sante",
    ["Armor"] = "Armure",
    ["Hunger"] = "Faim",
    ["Oxygen"] = "Oxygene",
    ["Props"] = "Props",
    ["Ammo"] = "Munitions",
    ["Agenda"] = "Agenda",
    ["Laws"] = "Lois",
    ["Laws - F1"] = "Lois - F1",
    ["Laws of the Land"] = "Lois du serveur",
    ["No laws are posted."] = "Aucune loi publiee.",
    ["Unknown"] = "Inconnu",
    ["Weapon"] = "Arme",
    ["Vehicle HUD"] = "HUD vehicule",
    ["Fuel"] = "Carburant",
    ["You Died"] = "Vous etes mort",
    ["Down but not out"] = "A terre, mais pas fini",
    ["Respawn when ready"] = "Reapparais quand tu es pret",
    ["Take a breath. You can respawn when the server allows it."] = "Respire. Tu pourras reapparaitre quand le serveur l'autorise.",
    ["Press {key} to respawn"] = "Appuie sur {key} pour reapparaitre",
    ["Any Key"] = "Toute touche",
    ["Mouse 1"] = "Souris 1",
    ["Space"] = "Espace",
    ["Enter"] = "Entree",
    ["Connection Interrupted"] = "Connexion interrompue",
    ["Trying to reconnect to the server..."] = "Tentative de reconnexion au serveur...",
    ["Disconnect"] = "Deconnexion",
    ["Retry"] = "Reessayer",
    ["Retry Now"] = "Reessayer maintenant",
    ["Waiting for server response"] = "En attente de la reponse du serveur",
    ["Auto reconnect in {seconds}s"] = "Reconnexion auto dans {seconds}s",
    ["Notifications"] = "Notifications",
    ["Death Feed"] = "Flux de morts",
    ["Voice HUD"] = "HUD vocal",
    ["Vote UI"] = "Interface de vote",
    ["Wanted / Lockdown"] = "Recherche / confinement",
    ["Lost Connection"] = "Connexion perdue",
    ["Actions Menu"] = "Menu d'actions",
    ["Choose a gesture"] = "Choisis un geste",
    ["Approve"] = "Approuver",
    ["Yes"] = "Oui",
    ["Skip"] = "Passer",
    ["Deny"] = "Refuser",
    ["No"] = "Non",
    ["Door"] = "Porte",
    ["Door Options"] = "Options de porte",
    ["Buy Door"] = "Acheter la porte",
    ["Sell Door"] = "Vendre la porte",
    ["Lock"] = "Verrouiller",
    ["Unlock"] = "Deverrouiller"
}

local de = {
    ["vehicle.health"] = "Leben",
    ["vehicle.fuel"] = "Kraftstoff",
    ["config.language"] = "Sprache",
    ["config.language_hint"] = "HUD-Beschriftungen mit vorhandenen Spracheintragen.",
    ["Overview"] = "Ubersicht",
    ["Theme"] = "Design",
    ["Weapon Selector"] = "Waffenauswahl",
    ["Death Screen"] = "Todesbildschirm",
    ["Scoreboard"] = "Spielerliste",
    ["Leaderboards"] = "Bestenlisten",
    ["Feeds"] = "Meldungen",
    ["Supported Scripts"] = "Unterstutzte Scripts",
    ["Credit System"] = "Kreditsystem",
    ["System Overview"] = "Systemubersicht",
    ["Core HUD behavior and quick workspace actions."] = "Grundverhalten des HUD und schnelle Aktionen.",
    ["Language & Localization"] = "Sprache und Lokalisierung",
    ["Choose the language used by built-in HUD and menu labels."] = "Wahle die Sprache fur integrierte HUD- und Menu-Beschriftungen.",
    ["Language"] = "Sprache",
    ["Active HUD layout"] = "Aktives HUD-Layout",
    ["Bar HUD"] = "Balken-HUD",
    ["Card HUD"] = "Karten-HUD",
    ["Clock source"] = "Uhrquelle",
    ["Real world time"] = "Echte Uhrzeit",
    ["Atmos / in-game time"] = "Atmos / Spielzeit",
    ["Admin command system"] = "Admin-Befehlssystem",
    ["Auto detect"] = "Automatisch erkennen",
    ["ServerGuard / Custom"] = "ServerGuard / Eigenes",
    ["Interface Sounds"] = "Interface-Sounds",
    ["Hover sound behavior for interactive HUD controls."] = "Sound beim Uberfahren interaktiver HUD-Elemente.",
    ["Enable hover sounds"] = "Hover-Sounds aktivieren",
    ["Hover sound preset"] = "Hover-Sound",
    ["Soft click"] = "Leiser Klick",
    ["Animation Menu"] = "Animationsmenu",
    ["DarkRP gesture/action menu override."] = "Ersatz fur das DarkRP Gesten-/Aktionsmenu.",
    ["Connection Overlay"] = "Verbindungsanzeige",
    ["Enable lost connection overlay"] = "Anzeige bei Verbindungsverlust aktivieren",
    ["Lost connection timeout"] = "Timeout bei Verbindungsverlust",
    ["Auto retry connection"] = "Automatisch erneut verbinden",
    ["Auto retry delay"] = "Wartezeit fur Neuversuch",
    ["Use background blur"] = "Hintergrund weichzeichnen",
    ["Show disconnect button"] = "Trennen-Schaltflache zeigen",
    ["Apply"] = "Ubernehmen",
    ["Placement"] = "Platzierung",
    ["Placement Mode"] = "Platzierungsmodus",
    ["Save"] = "Speichern",
    ["Reset"] = "Zurucksetzen",
    ["Confirm"] = "Bestatigen",
    ["Cancel"] = "Abbrechen",
    ["Close"] = "Schliessen",
    ["Enabled"] = "Aktiviert",
    ["Disabled"] = "Deaktiviert",
    ["Title"] = "Titel",
    ["Subtitle"] = "Untertitel",
    ["Width"] = "Breite",
    ["Height"] = "Hohe",
    ["Preview"] = "Vorschau",
    ["Welcome"] = "Willkommen",
    ["Welcome to the Server"] = "Willkommen auf dem Server",
    ["Read the rules, respect the RP, and have a good time."] = "Lies die Regeln, respektiere RP und hab Spass.",
    ["Server Updates"] = "Server-Neuigkeiten",
    ["Rules"] = "Regeln",
    ["Website"] = "Webseite",
    ["Shop"] = "Shop",
    ["Respect staff and other players."] = "Respektiere Teammitglieder und andere Spieler.",
    ["Stay in character during RP situations."] = "Bleibe wahrend RP-Situationen in deiner Rolle.",
    ["Do not RDM, prop abuse, or exploit."] = "Kein RDM, Prop-Abuse oder Exploiting.",
    ["Use the scoreboard for quick player actions and server info."] = "Nutze die Spielerliste fur schnelle Aktionen und Serverinfos.",
    ["Wallet"] = "Geldbeutel",
    ["Health"] = "Leben",
    ["Armor"] = "Ristung",
    ["Hunger"] = "Hunger",
    ["Oxygen"] = "Sauerstoff",
    ["Ammo"] = "Munition",
    ["Laws"] = "Gesetze",
    ["Laws - F1"] = "Gesetze - F1",
    ["Laws of the Land"] = "Servergesetze",
    ["No laws are posted."] = "Keine Gesetze eingetragen.",
    ["Unknown"] = "Unbekannt",
    ["Weapon"] = "Waffe",
    ["Vehicle HUD"] = "Fahrzeug-HUD",
    ["Fuel"] = "Kraftstoff",
    ["You Died"] = "Du bist gestorben",
    ["Down but not out"] = "Am Boden, aber nicht raus",
    ["Respawn when ready"] = "Respawne, wenn du bereit bist",
    ["Take a breath. You can respawn when the server allows it."] = "Atme kurz durch. Du kannst respawnen, wenn der Server es erlaubt.",
    ["Press {key} to respawn"] = "Drucke {key} zum Respawn",
    ["Any Key"] = "Beliebige Taste",
    ["Mouse 1"] = "Maus 1",
    ["Space"] = "Leertaste",
    ["Enter"] = "Enter",
    ["Connection Interrupted"] = "Verbindung unterbrochen",
    ["Trying to reconnect to the server..."] = "Verbindung zum Server wird wiederhergestellt...",
    ["Disconnect"] = "Trennen",
    ["Retry"] = "Neu versuchen",
    ["Retry Now"] = "Jetzt neu versuchen",
    ["Waiting for server response"] = "Warte auf Serverantwort",
    ["Auto reconnect in {seconds}s"] = "Auto-Verbindung in {seconds}s",
    ["Notifications"] = "Benachrichtigungen",
    ["Death Feed"] = "Killfeed",
    ["Voice HUD"] = "Sprach-HUD",
    ["Vote UI"] = "Abstimmungs-UI",
    ["Wanted / Lockdown"] = "Gesucht / Lockdown",
    ["Lost Connection"] = "Verbindung verloren",
    ["Actions Menu"] = "Aktionsmenu",
    ["Choose a gesture"] = "Wahle eine Geste",
    ["Approve"] = "Annehmen",
    ["Yes"] = "Ja",
    ["Skip"] = "Uberspringen",
    ["Deny"] = "Ablehnen",
    ["No"] = "Nein",
    ["Door"] = "Tur",
    ["Door Options"] = "Turoptionen",
    ["Buy Door"] = "Tur kaufen",
    ["Sell Door"] = "Tur verkaufen",
    ["Lock"] = "Abschliessen",
    ["Unlock"] = "Aufschliessen"
}

local pt = {
    ["vehicle.health"] = "Vida",
    ["vehicle.fuel"] = "Combustivel",
    ["config.language"] = "Idioma",
    ["config.language_hint"] = "Rotulos do HUD com traducoes disponiveis.",
    ["Overview"] = "Visao geral",
    ["Theme"] = "Tema",
    ["Weapon Selector"] = "Seletor de armas",
    ["Death Screen"] = "Tela de morte",
    ["Scoreboard"] = "Placar",
    ["Leaderboards"] = "Rankings",
    ["Feeds"] = "Avisos",
    ["Supported Scripts"] = "Scripts suportados",
    ["Credit System"] = "Sistema de creditos",
    ["System Overview"] = "Visao geral do sistema",
    ["Core HUD behavior and quick workspace actions."] = "Comportamento principal do HUD e acoes rapidas.",
    ["Language & Localization"] = "Idioma e localizacao",
    ["Choose the language used by built-in HUD and menu labels."] = "Escolha o idioma usado nos rotulos integrados do HUD e dos menus.",
    ["Language"] = "Idioma",
    ["Active HUD layout"] = "Layout ativo do HUD",
    ["Bar HUD"] = "HUD em barra",
    ["Card HUD"] = "HUD em cartao",
    ["Clock source"] = "Fonte do relogio",
    ["Real world time"] = "Hora real",
    ["Atmos / in-game time"] = "Atmos / hora do jogo",
    ["Admin command system"] = "Sistema de comandos admin",
    ["Auto detect"] = "Detectar automaticamente",
    ["ServerGuard / Custom"] = "ServerGuard / personalizado",
    ["Interface Sounds"] = "Sons da interface",
    ["Hover sound behavior for interactive HUD controls."] = "Som ao passar o cursor nos controles do HUD.",
    ["Enable hover sounds"] = "Ativar sons ao passar o cursor",
    ["Hover sound preset"] = "Som ao passar o cursor",
    ["Soft click"] = "Clique suave",
    ["Animation Menu"] = "Menu de animacoes",
    ["DarkRP gesture/action menu override."] = "Substituicao do menu de gestos/acoes do DarkRP.",
    ["Connection Overlay"] = "Painel de conexao",
    ["Enable lost connection overlay"] = "Ativar painel de conexao perdida",
    ["Lost connection timeout"] = "Tempo para conexao perdida",
    ["Auto retry connection"] = "Tentar reconectar automaticamente",
    ["Auto retry delay"] = "Atraso da reconexao",
    ["Use background blur"] = "Usar desfoque no fundo",
    ["Show disconnect button"] = "Mostrar botao de desconectar",
    ["Apply"] = "Aplicar",
    ["Placement"] = "Posicionamento",
    ["Placement Mode"] = "Modo de posicionamento",
    ["Save"] = "Salvar",
    ["Reset"] = "Redefinir",
    ["Confirm"] = "Confirmar",
    ["Cancel"] = "Cancelar",
    ["Close"] = "Fechar",
    ["Enabled"] = "Ativado",
    ["Disabled"] = "Desativado",
    ["Title"] = "Titulo",
    ["Subtitle"] = "Subtitulo",
    ["Width"] = "Largura",
    ["Height"] = "Altura",
    ["Preview"] = "Previa",
    ["Welcome"] = "Bem-vindo",
    ["Welcome to the Server"] = "Bem-vindo ao servidor",
    ["Read the rules, respect the RP, and have a good time."] = "Leia as regras, respeite o RP e divirta-se.",
    ["Server Updates"] = "Novidades do servidor",
    ["Rules"] = "Regras",
    ["Website"] = "Site",
    ["Shop"] = "Loja",
    ["Respect staff and other players."] = "Respeite a equipe e os outros jogadores.",
    ["Stay in character during RP situations."] = "Fique no personagem durante situacoes RP.",
    ["Do not RDM, prop abuse, or exploit."] = "Nao faca RDM, abuso de props ou exploits.",
    ["Use the scoreboard for quick player actions and server info."] = "Use o placar para acoes rapidas e infos do servidor.",
    ["Wallet"] = "Carteira",
    ["Health"] = "Vida",
    ["Armor"] = "Armadura",
    ["Hunger"] = "Fome",
    ["Oxygen"] = "Oxigenio",
    ["Ammo"] = "Municao",
    ["Laws"] = "Leis",
    ["Laws - F1"] = "Leis - F1",
    ["Laws of the Land"] = "Leis do servidor",
    ["No laws are posted."] = "Nenhuma lei publicada.",
    ["Unknown"] = "Desconhecido",
    ["Weapon"] = "Arma",
    ["Vehicle HUD"] = "HUD do veiculo",
    ["Fuel"] = "Combustivel",
    ["You Died"] = "Voce morreu",
    ["Down but not out"] = "Caiu, mas nao acabou",
    ["Respawn when ready"] = "Renasca quando estiver pronto",
    ["Take a breath. You can respawn when the server allows it."] = "Respire. Voce pode renascer quando o servidor permitir.",
    ["Press {key} to respawn"] = "Pressione {key} para renascer",
    ["Any Key"] = "Qualquer tecla",
    ["Mouse 1"] = "Mouse 1",
    ["Space"] = "Espaco",
    ["Enter"] = "Enter",
    ["Connection Interrupted"] = "Conexao interrompida",
    ["Trying to reconnect to the server..."] = "Tentando reconectar ao servidor...",
    ["Disconnect"] = "Desconectar",
    ["Retry"] = "Tentar novamente",
    ["Retry Now"] = "Tentar agora",
    ["Waiting for server response"] = "Aguardando resposta do servidor",
    ["Auto reconnect in {seconds}s"] = "Reconectar em {seconds}s",
    ["Notifications"] = "Notificacoes",
    ["Death Feed"] = "Feed de mortes",
    ["Voice HUD"] = "HUD de voz",
    ["Vote UI"] = "Interface de votacao",
    ["Wanted / Lockdown"] = "Procurado / lockdown",
    ["Lost Connection"] = "Conexao perdida",
    ["Actions Menu"] = "Menu de acoes",
    ["Choose a gesture"] = "Escolha um gesto",
    ["Approve"] = "Aprovar",
    ["Yes"] = "Sim",
    ["Skip"] = "Pular",
    ["Deny"] = "Negar",
    ["No"] = "Nao",
    ["Door"] = "Porta",
    ["Door Options"] = "Opcoes da porta",
    ["Buy Door"] = "Comprar porta",
    ["Sell Door"] = "Vender porta",
    ["Lock"] = "Trancar",
    ["Unlock"] = "Destrancar"
}

DHUD.Language.Strings = {
    en = en,
    es = Merge(Merge({}, en), es),
    fr = Merge(Merge({}, en), fr),
    de = Merge(Merge({}, en), de),
    pt_br = Merge(Merge({}, en), pt)
}

function DHUD.Language.Current()
    local code = DHUD.Config and DHUD.Config.Language or "en"
    code = string.lower(tostring(code or "en"))

    if not DHUD.Language.Strings[code] then
        return "en"
    end

    return code
end

function DHUD.Language.Get(key, fallback)
    key = tostring(key or "")
    local code = DHUD.Language.Current()
    local strings = DHUD.Language.Strings[code] or DHUD.Language.Strings.en or {}
    local english = DHUD.Language.Strings.en or {}

    return strings[key] or english[key] or fallback or key
end

function DHUD.Language.Text(value)
    if value == nil then return "" end
    local text = tostring(value)
    if text == "" then return text end

    local translated = DHUD.Language.Get(text, text)
    if translated ~= text then return translated end

    local prefix, body = string.match(text, "^([%-%*]%s+)(.+)$")
    if prefix and body then
        return prefix .. DHUD.Language.Get(body, body)
    end

    return text
end

function DHUD.Language.Format(key, fallback, replacements)
    local text = DHUD.Language.Get(key, fallback)
    for name, value in next, (replacements or {}) do
        text = string.Replace(text, "{" .. tostring(name) .. "}", tostring(value))
    end
    return text
end

function DHUD.T(key, fallback)
    return DHUD.Language.Get(key, fallback)
end

function DHUD.L(text)
    return DHUD.Language.Text(text)
end

function DHUD.LFormat(key, fallback, replacements)
    return DHUD.Language.Format(key, fallback, replacements)
end
